### ISSUE TITLE
tests: ValueError: object arrays are not supported

### ISSUE THREAD

**Issue by ignatenkobrain** [nipy/nipy#407]
after updating scipy from 0.16.1 to 0.18

``` python
======================================================================
ERROR: nipy.modalities.fmri.fmristat.tests.test_FIAC.test_altprotocol
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/nipy-0.4.0/build/lib.linux-x86_64-2.7/nipy/modalities/fmri/fmristat/tests/test_FIAC.py", line 220, in test_altprotocol
    block, bT, bF = protocol(descriptions['block'], 'block', *delay.spectral)
  File "/builddir/build/BUILD/nipy-0.4.0/build/lib.linux-x86_64-2.7/nipy/modalities/fmri/fmristat/tests/test_FIAC.py", line 89, in protocol
    utils.events(times[k], f=h))
  File "/builddir/build/BUILD/nipy-0.4.0/build/lib.linux-x86_64-2.7/nipy/modalities/fmri/utils.py", line 341, in events
    e = e + g.subs(asymb, a) * f(T-time)
  File "/usr/lib/python2.7/site-packages/sympy/core/function.py", line 720, in __new__
    obj = super(AppliedUndef, cls).__new__(cls, *args, **options)
  File "/usr/lib/python2.7/site-packages/sympy/core/function.py", line 392, in __new__
    return result.evalf(mlib.libmpf.prec_to_dps(pr))
  File "/usr/lib/python2.7/site-packages/sympy/core/evalf.py", line 1385, in evalf
    result = evalf(self, prec + 4, options)
  File "/usr/lib/python2.7/site-packages/sympy/core/evalf.py", line 1284, in evalf
    re, im = x._eval_evalf(prec).as_real_imag()
  File "/usr/lib/python2.7/site-packages/sympy/core/function.py", line 468, in _eval_evalf
    return Float(self._imp_(*self.args), prec)
  File "/usr/lib64/python2.7/site-packages/scipy/interpolate/polyint.py", line 78, in __call__
    x, x_shape = self._prepare_x(x)
  File "/usr/lib64/python2.7/site-packages/scipy/interpolate/polyint.py", line 90, in _prepare_x
    x = _asarray_validated(x, check_finite=False, as_inexact=True)
  File "/usr/lib64/python2.7/site-packages/scipy/_lib/_util.py", line 231, in _asarray_validated
    raise ValueError('object arrays are not supported')
ValueError: object arrays are not supported
======================================================================
ERROR: nipy.modalities.fmri.fmristat.tests.test_FIAC.test_agreement
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/nipy-0.4.0/build/lib.linux-x86_64-2.7/nipy/modalities/fmri/fmristat/tests/test_FIAC.py", line 277, in test_agreement
    X, c, D = create_protocols()
  File "/builddir/build/BUILD/nipy-0.4.0/build/lib.linux-x86_64-2.7/nipy/modalities/fmri/fmristat/tests/test_FIAC.py", line 204, in create_protocols
    block, bTcons, bFcons = protocol(descriptions['block'], 'block', *delay.spectral)
  File "/builddir/build/BUILD/nipy-0.4.0/build/lib.linux-x86_64-2.7/nipy/modalities/fmri/fmristat/tests/test_FIAC.py", line 89, in protocol
    utils.events(times[k], f=h))
  File "/builddir/build/BUILD/nipy-0.4.0/build/lib.linux-x86_64-2.7/nipy/modalities/fmri/utils.py", line 341, in events
    e = e + g.subs(asymb, a) * f(T-time)
  File "/usr/lib/python2.7/site-packages/sympy/core/function.py", line 720, in __new__
    obj = super(AppliedUndef, cls).__new__(cls, *args, **options)
  File "/usr/lib/python2.7/site-packages/sympy/core/function.py", line 392, in __new__
    return result.evalf(mlib.libmpf.prec_to_dps(pr))
  File "/usr/lib/python2.7/site-packages/sympy/core/evalf.py", line 1385, in evalf
    result = evalf(self, prec + 4, options)
  File "/usr/lib/python2.7/site-packages/sympy/core/evalf.py", line 1284, in evalf
    re, im = x._eval_evalf(prec).as_real_imag()
  File "/usr/lib/python2.7/site-packages/sympy/core/function.py", line 468, in _eval_evalf
    return Float(self._imp_(*self.args), prec)
  File "/usr/lib64/python2.7/site-packages/scipy/interpolate/polyint.py", line 78, in __call__
    x, x_shape = self._prepare_x(x)
  File "/usr/lib64/python2.7/site-packages/scipy/interpolate/polyint.py", line 90, in _prepare_x
    x = _asarray_validated(x, check_finite=False, as_inexact=True)
  File "/usr/lib64/python2.7/site-packages/scipy/_lib/_util.py", line 231, in _asarray_validated
    raise ValueError('object arrays are not supported')
ValueError: object arrays are not supported
======================================================================
ERROR: nipy.modalities.fmri.fmristat.tests.test_FIAC.test_event_design
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/nipy-0.4.0/build/lib.linux-x86_64-2.7/nipy/modalities/fmri/fmristat/tests/test_FIAC.py", line 299, in test_event_design
    Xblock, cblock = design.event_design(block[bkeep], t, hrfs=delay.spectral)
  File "/builddir/build/BUILD/nipy-0.4.0/build/lib.linux-x86_64-2.7/nipy/modalities/fmri/design.py", line 183, in event_design
    term = events(event_spec['time'], amplitudes=e_X[n], f=h)
  File "/builddir/build/BUILD/nipy-0.4.0/build/lib.linux-x86_64-2.7/nipy/modalities/fmri/utils.py", line 341, in events
    e = e + g.subs(asymb, a) * f(T-time)
  File "/usr/lib/python2.7/site-packages/sympy/core/function.py", line 720, in __new__
    obj = super(AppliedUndef, cls).__new__(cls, *args, **options)
  File "/usr/lib/python2.7/site-packages/sympy/core/function.py", line 392, in __new__
    return result.evalf(mlib.libmpf.prec_to_dps(pr))
  File "/usr/lib/python2.7/site-packages/sympy/core/evalf.py", line 1385, in evalf
    result = evalf(self, prec + 4, options)
  File "/usr/lib/python2.7/site-packages/sympy/core/evalf.py", line 1284, in evalf
    re, im = x._eval_evalf(prec).as_real_imag()
  File "/usr/lib/python2.7/site-packages/sympy/core/function.py", line 468, in _eval_evalf
    return Float(self._imp_(*self.args), prec)
  File "/usr/lib64/python2.7/site-packages/scipy/interpolate/polyint.py", line 78, in __call__
    x, x_shape = self._prepare_x(x)
  File "/usr/lib64/python2.7/site-packages/scipy/interpolate/polyint.py", line 90, in _prepare_x
    x = _asarray_validated(x, check_finite=False, as_inexact=True)
  File "/usr/lib64/python2.7/site-packages/scipy/_lib/_util.py", line 231, in _asarray_validated
    raise ValueError('object arrays are not supported')
ValueError: object arrays are not supported
----------------------------------------------------------------------
```

**Comment by matthew-brett** [comment]
Very sorry to be slow to get back to you.  This is a problem with a clash between scipy and sympy.  Would you mind testing against the latest master to confirm that this error is fixed?

**Comment by keszybz** [comment]
Still the same with:
python2-2.7.13-2.fc26.x86_64
sympy-1.0-4.fc26.noarch
python2-scipy-0.18.0-2.fc26.x86_64
```
======================================================================
ERROR: nipy.modalities.fmri.fmristat.tests.test_FIAC.test_altprotocol
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/nipy-0.4.0/build/lib.linux-x86_64-2.7/nipy/modalities/fmri/fmristat/tests/test_FIAC.py", line 220, in test_altprotocol
    block, bT, bF = protocol(descriptions['block'], 'block', *delay.spectral)
  File "/builddir/build/BUILD/nipy-0.4.0/build/lib.linux-x86_64-2.7/nipy/modalities/fmri/fmristat/tests/test_FIAC.py", line 89, in protocol
    utils.events(times[k], f=h))
  File "/builddir/build/BUILD/nipy-0.4.0/build/lib.linux-x86_64-2.7/nipy/modalities/fmri/utils.py", line 341, in events
    e = e + g.subs(asymb, a) * f(T-time)
  File "/usr/lib/python2.7/site-packages/sympy/core/function.py", line 720, in __new__
    obj = super(AppliedUndef, cls).__new__(cls, *args, **options)
  File "/usr/lib/python2.7/site-packages/sympy/core/function.py", line 392, in __new__
    return result.evalf(mlib.libmpf.prec_to_dps(pr))
  File "/usr/lib/python2.7/site-packages/sympy/core/evalf.py", line 1385, in evalf
    result = evalf(self, prec + 4, options)
  File "/usr/lib/python2.7/site-packages/sympy/core/evalf.py", line 1284, in evalf
    re, im = x._eval_evalf(prec).as_real_imag()
  File "/usr/lib/python2.7/site-packages/sympy/core/function.py", line 468, in _eval_evalf
    return Float(self._imp_(*self.args), prec)
  File "/usr/lib64/python2.7/site-packages/scipy/interpolate/polyint.py", line 78, in __call__
    x, x_shape = self._prepare_x(x)
  File "/usr/lib64/python2.7/site-packages/scipy/interpolate/polyint.py", line 90, in _prepare_x
    x = _asarray_validated(x, check_finite=False, as_inexact=True)
  File "/usr/lib64/python2.7/site-packages/scipy/_lib/_util.py", line 231, in _asarray_validated
    raise ValueError('object arrays are not supported')
ValueError: object arrays are not supported
======================================================================
ERROR: nipy.modalities.fmri.fmristat.tests.test_FIAC.test_agreement
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/nipy-0.4.0/build/lib.linux-x86_64-2.7/nipy/modalities/fmri/fmristat/tests/test_FIAC.py", line 277, in test_agreement
    X, c, D = create_protocols()
  File "/builddir/build/BUILD/nipy-0.4.0/build/lib.linux-x86_64-2.7/nipy/modalities/fmri/fmristat/tests/test_FIAC.py", line 204, in create_protocols
    block, bTcons, bFcons = protocol(descriptions['block'], 'block', *delay.spectral)
  File "/builddir/build/BUILD/nipy-0.4.0/build/lib.linux-x86_64-2.7/nipy/modalities/fmri/fmristat/tests/test_FIAC.py", line 89, in protocol
    utils.events(times[k], f=h))
  File "/builddir/build/BUILD/nipy-0.4.0/build/lib.linux-x86_64-2.7/nipy/modalities/fmri/utils.py", line 341, in events
    e = e + g.subs(asymb, a) * f(T-time)
  File "/usr/lib/python2.7/site-packages/sympy/core/function.py", line 720, in __new__
    obj = super(AppliedUndef, cls).__new__(cls, *args, **options)
  File "/usr/lib/python2.7/site-packages/sympy/core/function.py", line 392, in __new__
    return result.evalf(mlib.libmpf.prec_to_dps(pr))
  File "/usr/lib/python2.7/site-packages/sympy/core/evalf.py", line 1385, in evalf
    result = evalf(self, prec + 4, options)
  File "/usr/lib/python2.7/site-packages/sympy/core/evalf.py", line 1284, in evalf
    re, im = x._eval_evalf(prec).as_real_imag()
  File "/usr/lib/python2.7/site-packages/sympy/core/function.py", line 468, in _eval_evalf
    return Float(self._imp_(*self.args), prec)
  File "/usr/lib64/python2.7/site-packages/scipy/interpolate/polyint.py", line 78, in __call__
    x, x_shape = self._prepare_x(x)
  File "/usr/lib64/python2.7/site-packages/scipy/interpolate/polyint.py", line 90, in _prepare_x
    x = _asarray_validated(x, check_finite=False, as_inexact=True)
  File "/usr/lib64/python2.7/site-packages/scipy/_lib/_util.py", line 231, in _asarray_validated
    raise ValueError('object arrays are not supported')
ValueError: object arrays are not supported
======================================================================
ERROR: nipy.modalities.fmri.fmristat.tests.test_FIAC.test_event_design
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/nipy-0.4.0/build/lib.linux-x86_64-2.7/nipy/modalities/fmri/fmristat/tests/test_FIAC.py", line 299, in test_event_design
    Xblock, cblock = design.event_design(block[bkeep], t, hrfs=delay.spectral)
  File "/builddir/build/BUILD/nipy-0.4.0/build/lib.linux-x86_64-2.7/nipy/modalities/fmri/design.py", line 183, in event_design
    term = events(event_spec['time'], amplitudes=e_X[n], f=h)
  File "/builddir/build/BUILD/nipy-0.4.0/build/lib.linux-x86_64-2.7/nipy/modalities/fmri/utils.py", line 341, in events
    e = e + g.subs(asymb, a) * f(T-time)
  File "/usr/lib/python2.7/site-packages/sympy/core/function.py", line 720, in __new__
    obj = super(AppliedUndef, cls).__new__(cls, *args, **options)
  File "/usr/lib/python2.7/site-packages/sympy/core/function.py", line 392, in __new__
    return result.evalf(mlib.libmpf.prec_to_dps(pr))
  File "/usr/lib/python2.7/site-packages/sympy/core/evalf.py", line 1385, in evalf
    result = evalf(self, prec + 4, options)
  File "/usr/lib/python2.7/site-packages/sympy/core/evalf.py", line 1284, in evalf
    re, im = x._eval_evalf(prec).as_real_imag()
  File "/usr/lib/python2.7/site-packages/sympy/core/function.py", line 468, in _eval_evalf
    return Float(self._imp_(*self.args), prec)
  File "/usr/lib64/python2.7/site-packages/scipy/interpolate/polyint.py", line 78, in __call__
    x, x_shape = self._prepare_x(x)
  File "/usr/lib64/python2.7/site-packages/scipy/interpolate/polyint.py", line 90, in _prepare_x
    x = _asarray_validated(x, check_finite=False, as_inexact=True)
  File "/usr/lib64/python2.7/site-packages/scipy/_lib/_util.py", line 231, in _asarray_validated
    raise ValueError('object arrays are not supported')
ValueError: object arrays are not supported
----------------------------------------------------------------------
Ran 2599 tests in 273.665s
FAILED (SKIP=1, errors=3)
```

**Comment by matthew-brett** [comment]
Current nipy version (0.4.1) should fix this - can you confirm?

**Comment by keszybz** [comment]
Yep, it's fixed [https://koji.fedoraproject.org/koji/taskinfo?taskID=17819353]. Thanks!
